Add : user, product 모델링 추가
wecode-bootcamp-korea/13-FORKFOLK-backend pull request #2
Opened 2020-10-21 12:15 UTC by Hyoniii

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-22 06:07 UTC, lordmyshepherd requested changes

2020-10-22 06:07 UTC, lordmyshepherd commented on product/models.py
> +    orders      = models.ManyToManyField('user.Order',through='Cart', related_name='orders')
Order model이 user app에 존재하나요??
```suggestion
    orders      = models.ManyToManyField('order.Order',through='Cart', related_name='orders')
```
Order app을 따로 만들어서 분리해주세요~

2020-10-22 06:07 UTC, lordmyshepherd commented on product/models.py
> +class RelatedProduct(models.Model):
상품과 many to many 관계를 만들어주세요~
`self` 속성을 사용해보세요!
![image](https://user-images.githubusercontent.com/53214510/96830033-ad878100-1475-11eb-8f0e-20a344c2c7a7.png)

2020-10-22 06:07 UTC, lordmyshepherd commented on user/models.py
> +    created_at     = models.DateTimeField(auto_now_add=True)
updated_at 도 추가해주세요~~
auto_now=True 속성을 활용해서 만들어보세요~

2020-10-22 06:07 UTC, lordmyshepherd commented on product/models.py
> +# Create your models here.
주석은 지워주세요~
```suggestion
```

2020-10-22 11:07 UTC, Hyoniii commented on product/models.py
> +# Create your models here.
넵 지웠습니다

2020-10-22 11:07 UTC, Hyoniii commented on user/models.py
> +    created_at     = models.DateTimeField(auto_now_add=True)
넵

2020-10-22 11:29 UTC, Hyoniii commented on product/models.py
> +    orders      = models.ManyToManyField('user.Order',through='Cart', related_name='orders')
넵

2020-10-23 08:15 UTC, jamessoun93 requested changes
`user/views.py` 내용 빼고 올려주세요!

2020-10-23 12:20 UTC, merged